@ECHO SET ENVIRONMENT PATH
@SET MSYS2_BIN=C:\msys64\usr\bin
@REM @SET CC65_BIN=C:\cc65-snapshot-win32\bin
@SET PATH=%PATH%;%CC65_BIN%;%MSYS2_BIN%
@ECHO CC65_BIN=%CC65_BIN%
@ECHO MSYS2_BIN=%MSYS2_BIN%
